def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger'
]

pipeline {
    agent any
    environment {
        cluster = vproprod
        service = vproappprod-svc
    }

    stages {
        stage('Deploy to prod ecs') {
            steps {
                withAWS(credentials: 'awscreds', region: ap-south-1) {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }   

    post {
        always {
            echo 'Slack Notification.'
            slackSend channel: '#k8scicd',
            color: COLOR_MAP[currentBuild.currentResult],
            message: "*${currentBuild.currentResult}:* job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}


